import { dynamicTool, jsonSchema, stepCountIs, streamText, type ModelMessage, type ToolSet } from 'ai'
import { BrowserWindow, type WebContents } from 'electron'
import type {
  ChatAttachment,
  ChatDoneEvent,
  ChatErrorEvent,
  ChatMessage,
  Conversation,
  ToolRequestEvent
} from '../shared/types'
import { appendMessage, getConversation, replaceMessages, updateConversation } from './conversations'
import { getModel } from './providers'
import { getProvider, listModels } from './registry'
import { supportsThinking } from '../shared/modelCatalog'
import { getProject, retrieve } from './projects'
import { exposedTools } from './mcp'
import { enabledSkills, getSkillBody } from './skills'
import { appendMemory, getMemory } from './memory'
import { renderDocPreviewHtml, saveDocumentFromTool, type OfficeFormat } from './office'
import type { DocumentPreviewEvent } from '../shared/types'
import { getMathFormat } from './settings'
import { mathInstruction } from '../shared/mathPrompt'

const active = new Map<string, AbortController>()

// ---- tool approval plumbing ----
const pendingApprovals = new Map<string, (allowed: boolean) => void>()
const sessionAllowed = new Set<string>() // "server:tool" allowed for the rest of the session

export function respondToolRequest(requestId: string, decision: 'allow' | 'always' | 'deny'): void {
  const resolve = pendingApprovals.get(requestId)
  if (!resolve) return
  pendingApprovals.delete(requestId)
  resolve(decision !== 'deny')
  if (decision === 'always') {
    const [, key] = requestId.split('|', 2)
    if (key) sessionAllowed.add(key)
  }
}

function requestApproval(
  sender: WebContents,
  conversationId: string,
  serverName: string,
  toolName: string,
  args: unknown
): Promise<boolean> {
  const key = `${serverName}:${toolName}`
  if (sessionAllowed.has(key)) return Promise.resolve(true)
  const requestId = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}|${key}`
  return new Promise<boolean>((resolve) => {
    pendingApprovals.set(requestId, resolve)
    const event: ToolRequestEvent = { requestId, conversationId, serverName, toolName, args }
    if (!sender.isDestroyed()) sender.send('chat:tool-request', event)
    // fail closed if nobody answers
    setTimeout(() => {
      if (pendingApprovals.has(requestId)) {
        pendingApprovals.delete(requestId)
        resolve(false)
      }
    }, 10 * 60 * 1000)
  })
}

export function stopChat(conversationId: string): void {
  active.get(conversationId)?.abort()
}

/** Append the user message, then stream the assistant reply to the renderer.
 *  When `model` is given (e.g. Autopilot routing), the conversation is switched
 *  to that model first so the reply is generated by — and recorded against — it. */
export async function sendChat(
  sender: WebContents,
  conversationId: string,
  text: string,
  attachments?: ChatAttachment[],
  model?: { providerId: string; modelId: string }
): Promise<void> {
  if (model) updateConversation(conversationId, { providerId: model.providerId, modelId: model.modelId })
  appendMessage(conversationId, {
    role: 'user',
    content: text,
    attachments: attachments?.length ? attachments : undefined
  })
  await run(sender, conversationId)
}

/**
 * One-shot difficulty classification for Autopilot's optional "cheap model helper"
 * (toggleable in the UI). Asks a cheap model to label a message easy/medium/hard.
 * Best-effort: any failure returns null so the caller falls back to the heuristic.
 */
export async function classifyDifficulty(
  providerId: string,
  modelId: string,
  text: string
): Promise<'easy' | 'medium' | 'hard' | null> {
  try {
    const { generateText } = await import('ai')
    const { text: out } = await generateText({
      model: getModel(providerId, modelId),
      prompt:
        'Classify how much reasoning power the following user request needs. Reply with ONLY one word: ' +
        'easy (simple facts, chit-chat, short rewrites), medium (normal explanations, moderate code), ' +
        'or hard (complex reasoning, tricky math/proofs, large or subtle code, deep analysis).\n\nREQUEST:\n' +
        text.slice(0, 2000)
    })
    const w = out.toLowerCase()
    if (w.includes('hard')) return 'hard'
    if (w.includes('easy')) return 'easy'
    if (w.includes('medium')) return 'medium'
    return null
  } catch {
    return null
  }
}

/**
 * Transcribe a short voice recording (a WAV data URL from the composer's
 * dictation button) to text. The browser Speech Recognition API does not work
 * in Electron, so we send the audio to a Gemini model (which accepts audio
 * input) using the user's own Google key. Returns the text, or a friendly error.
 */
export async function transcribeAudio(dataUrl: string): Promise<{ text?: string; error?: string }> {
  try {
    if (!dataUrl.startsWith('data:')) return { error: 'No audio was recorded.' }
    const semi = dataUrl.indexOf(';')
    const mediaType = semi > 5 ? dataUrl.slice(5, semi) : 'audio/wav'
    const models = await listModels()
    const google = models.filter((m) => m.providerId === 'google')
    // Prefer a cheap, fast, audio-capable Gemini flash model.
    const pick =
      google.find((m) => /flash-lite/i.test(m.modelId)) ||
      google.find((m) => /flash/i.test(m.modelId)) ||
      google[0]
    if (!pick) {
      return {
        error: 'Dictation needs a Google (Gemini) API key. Add one in Providers, then try again.'
      }
    }
    const { generateText } = await import('ai')
    const { text } = await generateText({
      model: getModel(pick.providerId, pick.modelId),
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text:
                'Transcribe the following audio to plain text. Output ONLY the exact words spoken — ' +
                'no preamble, no quotation marks, no commentary. If there is no clear speech, output nothing.'
            },
            { type: 'file', mediaType, data: dataUrl }
          ]
        }
      ],
      abortSignal: AbortSignal.timeout(30_000)
    })
    return { text: text.trim() }
  } catch (err) {
    return { error: err instanceof Error ? err.message : String(err) }
  }
}

/**
 * Drop the trailing assistant message and stream a fresh reply. When `model` is
 * given, switch the conversation to that model first — this powers the
 * "regenerate with a different model" (second opinion) button.
 */
export async function regenerateChat(
  sender: WebContents,
  conversationId: string,
  model?: { providerId: string; modelId: string }
): Promise<void> {
  if (model) updateConversation(conversationId, { providerId: model.providerId, modelId: model.modelId })
  const conv = getConversation(conversationId)
  if (conv.messages.at(-1)?.role === 'assistant') {
    replaceMessages(conversationId, conv.messages.slice(0, -1))
  }
  await run(sender, conversationId)
}

/**
 * Edit a past user message and re-run from there: everything after the edited
 * message is dropped, the message text is replaced (its attachments kept), and
 * a fresh reply is streamed.
 */
export async function editAndResend(
  sender: WebContents,
  conversationId: string,
  index: number,
  newText: string
): Promise<void> {
  const conv = getConversation(conversationId)
  const orig = conv.messages[index]
  if (!orig || orig.role !== 'user') return
  const head = conv.messages.slice(0, index)
  replaceMessages(conversationId, [
    ...head,
    { role: 'user', content: newText, attachments: orig.attachments }
  ])
  await run(sender, conversationId)
}

function toModelMessage(m: ChatMessage): ModelMessage {
  const attachments = m.attachments ?? []
  const textDocs = attachments.filter((a) => !a.image)
  const images = attachments.filter((a) => a.image)

  let content = m.content
  if (textDocs.length > 0) {
    const blocks = textDocs.map((a) => `[Attached file: ${a.name}]\n${a.text ?? ''}`).join('\n\n')
    content = content ? `${content}\n\n${blocks}` : blocks
  }

  // Images go as real file parts (vision models); text-only models will error clearly
  if (m.role === 'user' && images.length > 0) {
    return {
      role: 'user',
      content: [
        ...(content ? [{ type: 'text' as const, text: content }] : []),
        ...images.map((a) => ({
          type: 'file' as const,
          // data URL format: data:<mediaType>;base64,....
          mediaType: a.image!.slice(5, a.image!.indexOf(';')) || 'image/png',
          data: a.image!
        }))
      ]
    }
  }
  return { role: m.role, content }
}

/**
 * Extended-thinking options per provider kind. Returned as streamText
 * providerOptions; unknown/OpenAI-compatible providers get none (some, like
 * gpt-oss, stream reasoning on their own — we display whatever arrives).
 */
function thinkingOptions(
  providerId: string,
  modelId: string,
  effort: 'low' | 'medium' | 'high' = 'medium'
): Parameters<typeof streamText>[0]['providerOptions'] {
  const kind = getProvider(providerId)?.kind
  // Never send a thinking option to a model that doesn't accept one (e.g.
  // reasoningEffort to gpt-4o errors) — mirrors the UI's toggle gating.
  if (!supportsThinking(kind, modelId)) return undefined
  // Effort → concrete per-provider reasoning budget.
  const budget = { low: 4000, medium: 10000, high: 24000 }[effort]
  switch (kind) {
    case 'anthropic':
      return { anthropic: { thinking: { type: 'enabled', budgetTokens: budget } } }
    case 'openai':
      return { openai: { reasoningEffort: effort } }
    case 'google':
      return { google: { thinkingConfig: { includeThoughts: true, thinkingBudget: budget } } }
    default:
      return undefined
  }
}

/**
 * Keyless web search via DuckDuckGo's HTML endpoint. Returns a short list of
 * result titles + snippets + URLs as plain text for the model to read. No API
 * key required. Best-effort: on any failure it returns an explanatory string
 * rather than throwing, so the chat keeps working.
 */
interface SearchResult {
  title: string
  url: string
  snippet: string
}

const SEARCH_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'

// Most a single reply may search. Prevents runaway models from firing dozens of
// searches that flood the chat and blow out the context window. Kept low so a
// search turn stays fast (each search is a few parallel HTTP calls).
const MAX_WEB_SEARCHES = 4

// Per-source fetch budget. Short so a slow/blocked source can't stall the whole
// reply — the other sources still return and the model answers from those.
const SEARCH_TIMEOUT_MS = 6_000

// Current-events / freshness intent: when the query looks like it wants the
// latest happenings, news becomes the PRIMARY source and the encyclopedia is
// demoted (so "what's new today" doesn't come back as Wikipedia articles).
const NEWS_INTENT =
  /\b(news|today|todays|latest|current|currently|recent|recently|now|this (week|month|morning|year)|breaking|update|updates|happening|headlines?|score|scores|results?|price|prices|stock|weather|forecast|released?|launch(ed|ing)?|announce|died|election|20\d\d)\b/i

/**
 * Keyless web search across THREE independent sources in parallel, merged and
 * de-duplicated: DuckDuckGo (general web, when not rate-limited), Wikipedia
 * (reliable facts + an intro extract for the top hit) and Google News (fresh
 * current-events coverage). Using several sources means one being blocked no
 * longer drops the model back to stale training data. Best-effort: every source
 * fails soft to [], and the whole thing returns an explanatory string (never
 * throws) if nothing at all comes back.
 */
export async function webSearch(query: string): Promise<string> {
  const q = query.trim()
  if (!q) return 'No search query was provided. Call web_search again with a concise "query" string.'
  const newsy = NEWS_INTENT.test(q)

  // Three keyless sources, all fired in parallel and failing soft to []:
  //   • Google News RSS — fresh current-events coverage (headline + source + date)
  //   • DuckDuckGo Instant Answer — a direct answer / entity summary for the query
  //   • Wikipedia — reliable background facts + an intro extract for the top hit
  // News-intent queries put News FIRST and drop Wikipedia to the back so
  // "what's new today" returns actual headlines, not encyclopedia articles.
  const [news, ddg, wiki] = await Promise.all([
    searchNews(q).catch(() => [] as SearchResult[]),
    searchDuckDuckGo(q).catch(() => [] as SearchResult[]),
    searchWikipedia(q).catch(() => [] as SearchResult[])
  ])

  const ordered = newsy ? [...news, ...ddg, ...wiki] : [...ddg, ...wiki, ...news]

  const merged: SearchResult[] = []
  const seen = new Set<string>()
  for (const r of ordered) {
    if (!r.url || !r.title) continue
    const key = r.url
      .replace(/^https?:\/\//, '')
      .replace(/\/$/, '')
      .toLowerCase()
    if (seen.has(key)) continue
    seen.add(key)
    merged.push(r)
  }
  if (merged.length === 0) {
    // Be explicit so the model doesn't silently fall back to stale training data.
    return `Live web search returned no results for "${q}". Tell the user you could not retrieve live results right now and that anything you say may be out of date — do NOT present old training data as current.`
  }
  const header = newsy
    ? `Live web results for "${q}" (freshest first). Synthesize these into a clear, specific answer and cite the URLs:`
    : `Live web results for "${q}". Base your answer on these and cite the URLs:`
  return (
    header +
    '\n\n' +
    merged
      .slice(0, 6)
      .map((r, n) => `${n + 1}. ${r.title}\n${r.snippet}\n${r.url}`)
      .join('\n\n')
  )
}

/**
 * DuckDuckGo Instant Answer API (the keyless JSON endpoint — NOT the bot-blocked
 * HTML SERP). Returns a direct abstract for the query plus a few related topics,
 * which covers general/definitional questions the news + encyclopedia sources
 * answer poorly.
 */
async function searchDuckDuckGo(query: string): Promise<SearchResult[]> {
  const res = await fetch(
    `https://api.duckduckgo.com/?q=${encodeURIComponent(query)}&format=json&no_html=1&skip_disambig=1&t=orbit`,
    { headers: { 'user-agent': SEARCH_UA }, signal: AbortSignal.timeout(SEARCH_TIMEOUT_MS) }
  )
  if (!res.ok) return []
  const j = (await res.json()) as {
    AbstractText?: string
    AbstractURL?: string
    Heading?: string
    RelatedTopics?: { Text?: string; FirstURL?: string }[]
  }
  const out: SearchResult[] = []
  if (j.AbstractText && j.AbstractURL) {
    out.push({
      title: j.Heading || query,
      url: j.AbstractURL,
      snippet: j.AbstractText.slice(0, 400)
    })
  }
  for (const t of j.RelatedTopics ?? []) {
    if (out.length >= 4) break
    if (t.Text && t.FirstURL) out.push({ title: t.Text.slice(0, 80), url: t.FirstURL, snippet: t.Text })
  }
  return out
}

/** Wikipedia search API + an intro extract for the top hit (reliable facts). */
async function searchWikipedia(query: string): Promise<SearchResult[]> {
  const api = 'https://en.wikipedia.org/w/api.php'
  const sres = await fetch(
    `${api}?action=query&list=search&srsearch=${encodeURIComponent(query)}&format=json&srlimit=4`,
    { headers: { 'user-agent': SEARCH_UA }, signal: AbortSignal.timeout(SEARCH_TIMEOUT_MS) }
  )
  if (!sres.ok) return []
  const sjson = (await sres.json()) as {
    query?: { search?: { title: string; snippet: string }[] }
  }
  const hits = sjson.query?.search ?? []
  if (hits.length === 0) return []
  const results: SearchResult[] = hits.map((h) => ({
    title: `${h.title} — Wikipedia`,
    url: `https://en.wikipedia.org/wiki/${encodeURIComponent(h.title.replace(/ /g, '_'))}`,
    snippet: stripHtml(h.snippet)
  }))
  // Enrich the top hit with its intro extract so the model gets real content,
  // not just a one-line snippet.
  try {
    const eres = await fetch(
      `${api}?action=query&prop=extracts&exintro=1&explaintext=1&titles=${encodeURIComponent(hits[0].title)}&format=json`,
      { headers: { 'user-agent': SEARCH_UA }, signal: AbortSignal.timeout(SEARCH_TIMEOUT_MS) }
    )
    if (eres.ok) {
      const ejson = (await eres.json()) as { query?: { pages?: Record<string, { extract?: string }> } }
      const extract = Object.values(ejson.query?.pages ?? {})[0]?.extract
      if (extract) results[0].snippet = extract.trim().slice(0, 350)
    }
  } catch {
    /* keep the plain snippet */
  }
  return results
}

/** Google News RSS — fresh, relevant current-events coverage, keyless. */
async function searchNews(query: string): Promise<SearchResult[]> {
  const res = await fetch(
    `https://news.google.com/rss/search?q=${encodeURIComponent(query)}&hl=en-US&gl=US&ceid=US:en`,
    { headers: { 'user-agent': SEARCH_UA }, signal: AbortSignal.timeout(SEARCH_TIMEOUT_MS) }
  )
  if (!res.ok) return []
  const xml = await res.text()
  const results: SearchResult[] = []
  for (const it of [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0, 6)) {
    const block = it[1]
    const rawTitle = stripHtml((block.match(/<title>([\s\S]*?)<\/title>/)?.[1] ?? '').replace(/<!\[CDATA\[|\]\]>/g, ''))
    const url = (block.match(/<link>([\s\S]*?)<\/link>/)?.[1] ?? '').trim()
    const pub = (block.match(/<pubDate>([\s\S]*?)<\/pubDate>/)?.[1] ?? '').trim()
    const source = stripHtml(block.match(/<source[^>]*>([\s\S]*?)<\/source>/)?.[1] ?? '')
    if (!rawTitle || !url) continue
    // Google News titles read "Headline - Source"; split the source out so the
    // headline is clean and the source is shown as attribution.
    const m = rawTitle.match(/^(.*?)\s+-\s+([^-]+)$/)
    const title = m ? m[1] : rawTitle
    const src = source || (m ? m[2] : '')
    const date = pub ? new Date(pub).toISOString().slice(0, 10) : ''
    const meta = [src, date].filter(Boolean).join(' · ')
    results.push({ title, url, snippet: meta ? `${meta} — news headline` : 'News headline' })
  }
  return results
}

function stripHtml(s: string): string {
  return s
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#x27;/g, "'")
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim()
}

function buildToolSet(sender: WebContents, conversationId: string, webSearchOn: boolean): ToolSet {
  const tools: ToolSet = {}

  // Keyless web search — available to any tool-capable model when enabled for
  // the conversation. No approval needed (read-only lookup).
  if (webSearchOn) {
    // Hard per-turn ceiling on searches. Some models (e.g. glm-4.7) will
    // otherwise fire ~20 near-identical searches, which (a) spams the chat with
    // cards and (b) balloons the context window because every prior result is
    // re-fed to the model on each step. After the cap we return a directive
    // telling the model to stop searching and answer from what it has.
    let searchCount = 0
    tools['web_search'] = dynamicTool({
      description:
        'Search the live public web (Google News, DuckDuckGo, Wikipedia) and get back the top results (title, snippet, URL). Use this for current events, "what\'s new / latest", recent releases, prices, scores, facts you are unsure about, or anything that may have changed after your training. Prefer ONE broad query that covers the whole question — never one search per item. Pass a concise "query" string, then STOP and write a specific answer citing the URLs.',
      // NOTE: query is intentionally NOT marked required — some openai-compat
      // models emit slightly different arg shapes, and a schema rejection would
      // surface as an ugly "tool didn't complete" error instead of a search.
      // execute() coerces the query out of whatever shape arrives.
      inputSchema: jsonSchema({
        type: 'object',
        properties: {
          query: { type: 'string', description: 'The search query (a few keywords or a question)' }
        }
      }),
      execute: async (args) => {
        const a = args as { query?: unknown; q?: unknown; search?: unknown; text?: unknown }
        const raw =
          typeof args === 'string' ? args : (a?.query ?? a?.q ?? a?.search ?? a?.text ?? '')
        const q = String(raw ?? '').trim()
        if (!q) return 'No search query was provided. Call web_search again with a concise "query" string (a few keywords).'
        searchCount += 1
        if (searchCount > MAX_WEB_SEARCHES) {
          return `You have already run ${MAX_WEB_SEARCHES} web searches — that is enough. STOP searching now and write a complete answer from the results you already have. Do not call web_search again.`
        }
        return webSearch(q)
      }
    })
  }

  // Persistent memory — writes only to the app's own memory.md, no approval needed
  tools['save_memory'] = dynamicTool({
    description:
      'Save a short fact to persistent memory so ALL future conversations remember it. Use whenever the user asks you to remember something (a preference, a name, a standing instruction).',
    inputSchema: jsonSchema({
      type: 'object',
      properties: {
        fact: { type: 'string', description: 'The fact to remember, one concise sentence' }
      },
      required: ['fact']
    }),
    execute: async (args) => {
      const fact = String((args as { fact: string }).fact ?? '').trim()
      if (!fact) return 'Nothing to save.'
      appendMemory(fact)
      return 'Saved to persistent memory.'
    }
  })

  // Native Office generation — the APP converts markdown to a real file, so this
  // works for any tool-capable model regardless of its own abilities. The save
  // dialog itself is the user's consent, so no separate approval step.
  tools['create_document'] = dynamicTool({
    description:
      'Create a real Microsoft Office file on the user\'s computer: Word (.docx), Excel (.xlsx) or PowerPoint (.pptx). ' +
      'You only provide the CONTENT as markdown — Orbit (this app) converts and saves it natively; you need no file-system access of your own. ' +
      'ALWAYS call this tool when the user asks for a Word/Excel/PowerPoint/Office document. Never say you cannot create files. ' +
      'Formatting: for xlsx use markdown tables (each table becomes a sheet); for pptx use # or ## headings as slide titles with bullets under them; for docx use normal markdown.',
    inputSchema: jsonSchema({
      type: 'object',
      properties: {
        format: { type: 'string', enum: ['docx', 'xlsx', 'pptx'], description: 'The file type to create' },
        filename: { type: 'string', description: 'Suggested file name without extension' },
        content: { type: 'string', description: 'The full document content as markdown' }
      },
      required: ['format', 'filename', 'content']
    }),
    execute: async (args) => {
      const { format, filename, content } = args as {
        format: OfficeFormat
        filename: string
        content: string
      }
      if (!['docx', 'xlsx', 'pptx'].includes(format)) return 'Unknown format — use docx, xlsx or pptx.'
      if (!content?.trim()) return 'No content provided — call again with the document content in markdown.'
      try {
        const win = BrowserWindow.fromWebContents(sender)
        const { message, filePath } = await saveDocumentFromTool(win, format, content, filename || 'document')
        if (filePath && !sender.isDestroyed()) {
          // show the document in the split-screen panel (like Claude Desktop)
          const event: DocumentPreviewEvent = {
            conversationId,
            format,
            filename: filename || 'document',
            path: filePath,
            html: await renderDocPreviewHtml(content, format, filePath)
          }
          sender.send('chat:document-preview', event)
        }
        return message
      } catch (err) {
        return `Creating the document failed: ${err instanceof Error ? err.message : String(err)}`
      }
    }
  })

  // Built-in skill loader — local read, no approval needed
  const skills = enabledSkills()
  if (skills.length > 0) {
    tools['read_skill'] = dynamicTool({
      description:
        'Load the full instructions of an available skill. Call this BEFORE performing a task that matches a skill description. Available skills: ' +
        skills.map((s) => `"${s.id}" (${s.description})`).join('; '),
      inputSchema: jsonSchema({
        type: 'object',
        properties: {
          skill: { type: 'string', enum: skills.map((s) => s.id), description: 'The skill id to load' }
        },
        required: ['skill']
      }),
      execute: async (args) => {
        try {
          return getSkillBody((args as { skill: string }).skill)
        } catch {
          return 'Unknown skill.'
        }
      }
    })
  }

  for (const t of exposedTools()) {
    tools[t.key] = dynamicTool({
      description: t.description,
      inputSchema: jsonSchema(t.inputSchema as Parameters<typeof jsonSchema>[0]),
      execute: async (args) => {
        const allowed = await requestApproval(sender, conversationId, t.serverName, t.toolName, args)
        if (!allowed) return 'The user declined this tool call. Continue without it.'
        try {
          return await t.call(args)
        } catch (err) {
          return `Tool call failed: ${err instanceof Error ? err.message : String(err)}`
        }
      }
    })
  }
  return tools
}

async function run(sender: WebContents, conversationId: string): Promise<void> {
  if (active.has(conversationId)) return

  const conv = getConversation(conversationId)
  const controller = new AbortController()
  active.set(conversationId, controller)
  let full = ''

  let reasoningFull = ''

  const emit = (channel: string, payload: unknown) => {
    if (!sender.isDestroyed()) sender.send(channel, payload)
  }
  const push = (text: string) => {
    full += text
    emit('chat:chunk', { conversationId, delta: text })
  }

  const startedAt = Date.now()
  let firstTokenAt = 0

  try {
    const model = getModel(conv.providerId, conv.modelId)
    const system = await buildSystemPrompt(conv)
    const tools = buildToolSet(sender, conversationId, conv.webSearch ?? false)
    const hasTools = Object.keys(tools).length > 0
    const providerOptions = conv.thinking
      ? thinkingOptions(conv.providerId, conv.modelId, conv.effort ?? 'medium')
      : undefined

    const result = streamText({
      model,
      system,
      messages: conv.messages.map(toModelMessage),
      abortSignal: controller.signal,
      ...(providerOptions ? { providerOptions } : {}),
      // When web search is on, keep the step ceiling low: combined with the
      // MAX_WEB_SEARCHES cap this stops a model looping on searches and eating
      // the context window. Non-search tool loops keep the roomier 14 steps.
      ...(hasTools ? { tools, stopWhen: stepCountIs(conv.webSearch ? 6 : 14) } : {})
    })

    // Buffer each tool call's input so its result renders as ONE combined card
    // (instead of a separate "calling" + "returned" pair).
    const pendingToolInput = new Map<string, unknown>()
    for await (const part of result.fullStream) {
      if (part.type === 'text-delta') {
        if (!firstTokenAt) firstTokenAt = Date.now()
        push(part.text)
      } else if (part.type === 'reasoning-delta') {
        if (!firstTokenAt) firstTokenAt = Date.now()
        reasoningFull += part.text
        emit('chat:chunk', { conversationId, delta: part.text, reasoning: true })
      } else if (part.type === 'tool-call') {
        pendingToolInput.set(part.toolCallId, part.input)
      } else if (part.type === 'tool-result') {
        push(toolCard(part.toolName, pendingToolInput.get(part.toolCallId), part.output))
        pendingToolInput.delete(part.toolCallId)
      } else if (part.type === 'tool-error') {
        // Stay silent — a failed lookup shouldn't spook the user; the model
        // retries and the answer stands on the searches that did work.
        pendingToolInput.delete(part.toolCallId)
      } else if (part.type === 'error') {
        throw part.error instanceof Error ? part.error : new Error(String(part.error))
      }
    }

    const usage = await result.totalUsage
    // Generation speed: output tokens ÷ seconds spent producing them (measured
    // from the first token so network/queue latency isn't counted).
    const elapsedSec = (Date.now() - (firstTokenAt || startedAt)) / 1000
    const tps =
      usage.outputTokens && elapsedSec > 0.05
        ? Math.round(usage.outputTokens / elapsedSec)
        : undefined
    const message: ChatMessage = {
      role: 'assistant',
      content: full,
      reasoning: reasoningFull || undefined,
      model: `${conv.providerId}/${conv.modelId}`,
      usage: { inputTokens: usage.inputTokens, outputTokens: usage.outputTokens },
      tps
    }
    appendMessage(conversationId, message)
    emit('chat:done', { conversationId, message } satisfies ChatDoneEvent)
  } catch (err) {
    if (controller.signal.aborted) {
      // Keep whatever streamed before the stop
      const message: ChatMessage = {
        role: 'assistant',
        content: full,
        reasoning: reasoningFull || undefined,
        model: `${conv.providerId}/${conv.modelId}`,
        aborted: true
      }
      if (full.length > 0) appendMessage(conversationId, message)
      emit('chat:done', { conversationId, message } satisfies ChatDoneEvent)
    } else {
      const message = err instanceof Error ? err.message : String(err)
      emit('chat:error', { conversationId, message } satisfies ChatErrorEvent)
    }
  } finally {
    active.delete(conversationId)
  }
}

function stringifyOutput(output: unknown): string {
  return typeof output === 'string' ? output : JSON.stringify(output)
}

// ---------- friendly tool-activity cards (Claude-style) ----------
// Tool calls/results are streamed into the reply wrapped in ⟦tool⟧…⟦/tool⟧
// sentinels (an optional ⟦body⟧ separates a collapsible body). ChatsView turns
// these into clean cards — a friendly one-line label and, for web search, a
// collapsible Sources list — instead of dumping the raw tool name + JSON.
function friendlyToolName(name: string): string {
  switch (name) {
    case 'web_search':
      return 'web search'
    case 'create_document':
      return 'document export'
    case 'save_memory':
      return 'memory'
    case 'read_skill':
      return 'skill'
    default:
      return name.replace(/_/g, ' ')
  }
}

function capitalize(s: string): string {
  return s ? s[0].toUpperCase() + s.slice(1) : s
}

// ONE compact card per tool call (call + result combined). For web search: a
// collapsible "🔎 Searched the web — query" whose body is the Sources list when
// we have results, or just the summary line when we don't — never a scary
// "no results" / error card.
function toolCard(name: string, input: unknown, output: unknown): string {
  if (name === 'web_search') {
    const q = (input as { query?: unknown } | null)?.query
    const query = typeof q === 'string' ? q : ''
    const summary = `🔎 Searched the web${query ? ` — “${query}”` : ''}`
    const sources = webSourcesMarkdown(stringifyOutput(output))
    return sources
      ? `\n\n⟦tool⟧${summary}⟦body⟧${sources}⟦/tool⟧\n\n`
      : `\n\n⟦tool⟧${summary}⟦/tool⟧\n\n`
  }
  return `\n\n⟦tool⟧✅ ${capitalize(friendlyToolName(name))} done⟦/tool⟧\n\n`
}

// Parse webSearch()'s "N. title\nsnippet\nurl" blocks back into a tidy numbered
// list of markdown links for the Sources card. Returns null if nothing parses.
function webSourcesMarkdown(output: string): string | null {
  const items: string[] = []
  for (const block of output.split('\n\n')) {
    const lines = block
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
    if (lines.length === 0) continue
    const title = lines[0].replace(/^\d+\.\s*/, '').trim()
    const url = lines.find((l) => /^https?:\/\//i.test(l))
    if (title && url) items.push(`${items.length + 1}. [${title}](${url})`)
  }
  return items.length ? items.join('\n') : null
}

/**
 * Conversation system prompt + (for project conversations) the project's
 * instructions and the most relevant file excerpts for the latest user message.
 */
async function buildSystemPrompt(conv: Conversation): Promise<string | undefined> {
  const parts: string[] = []
  if (conv.systemPrompt) parts.push(conv.systemPrompt)

  // Ground the model in the ACTUAL current date. Without this, models answer as
  // if it were still their training-cutoff year and dismiss genuinely current
  // (e.g. 2026) news or search results as "future-dated", "synthetic" or a
  // search error — exactly the failure users hit with web search on.
  const now = new Date()
  const today = now.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
  parts.push(
    `Today's date is ${today}. This is the real, current date — your training data ends before today, so the present is genuinely later than your built-in knowledge. Treat ${now.getFullYear()} and later as the PRESENT, not the future: any news, events, releases or search results dated ${now.getFullYear()} or later are current and real. Never insist it is an earlier year, and never dismiss recent or newer-than-your-training dates as "synthetic", "anomalous", "future-dated", or a search-index error.`
  )

  // Built-in maths formatting fix — every model is told how to write maths so the
  // app renders it correctly (LaTeX by default, or plain Unicode if the user prefers).
  parts.push(mathInstruction(getMathFormat()))

  // Native Office support: the APP does the file conversion, so no model may
  // refuse document requests for lack of file abilities or "permission".
  parts.push(
    'Document creation — IMPORTANT: This app (Orbit) natively creates Microsoft Office files from your markdown output; ' +
      'the app itself performs all file operations, so you always have this capability regardless of your own limitations. ' +
      'When the user asks for a Word document, Excel workbook, PowerPoint presentation or similar Office file: ' +
      '(1) if you have the create_document tool, call it with the full content as markdown; ' +
      '(2) if you cannot use tools, write the complete document content in markdown in your reply — the app can still save it as a real file from there. ' +
      'Use markdown tables for Excel content and # / ## headings (one per slide) with bullets for PowerPoint content. ' +
      'NEVER refuse such a request by saying you cannot create files, lack permission, or lack the capability.'
  )

  // Web search is on for this chat — make the model actually USE it for anything
  // time-sensitive instead of answering from (stale) memory and hallucinating.
  if (conv.webSearch) {
    parts.push(
      'Web search is ENABLED for this conversation. For ANY question about current events, recent ' +
        'releases, latest versions/models, prices, schedules, dates, or anything that may have changed ' +
        'after your training cutoff, you MUST call the web_search tool FIRST and base your answer ONLY on ' +
        'the results it returns (cite the source URLs). Do NOT answer such questions from memory, and NEVER ' +
        'present training-data guesses as current fact. ' +
        'Search EFFICIENTLY and FAST: prefer ONE broad query that covers the whole question (a single good ' +
        'query usually returns enough to answer many sub-parts); only search again if the first results clearly ' +
        'miss the point. Do NOT run a separate search for every item, year or name. ' +
        `You may run at MOST ${MAX_WEB_SEARCHES} searches per reply — after that the tool will refuse and you must answer from what you have. ` +
        'As soon as you have enough, STOP searching and WRITE THE COMPLETE ANSWER — every reply must end with ' +
        'a written answer for the user, never just a series of searches. ' +
        'The results reflect the LIVE web as of today, so treat them as current fact even when their dates look ' +
        'newer than your training data — do NOT call them future-dated, synthetic or a search error. ' +
        'If web_search returns no results, say so plainly and warn the user the information may be out of ' +
        'date — do not invent an answer.'
    )
  }

  // Persistent memory — facts saved across conversations
  const memory = getMemory().trim()
  if (memory) {
    parts.push(
      `Persistent memory — facts the user asked you to remember in earlier conversations (use them when relevant; save new ones with the save_memory tool):\n${memory}`
    )
  }

  // Skills: always list descriptions; inject full body when the latest user
  // message mentions the skill (works for models without tool support too).
  const skills = enabledSkills()
  if (skills.length > 0) {
    const lastUserText =
      [...conv.messages].reverse().find((m) => m.role === 'user')?.content.toLowerCase() ?? ''
    const triggered = skills.filter((s) => {
      const names = [s.id, s.name].map((n) => n.toLowerCase())
      return names.some((n) => n.length > 2 && lastUserText.includes(n))
    })
    parts.push(
      'Available skills (task-specific instructions):\n' +
        skills.map((s) => `- ${s.id}: ${s.description}`).join('\n') +
        '\nIf a task matches a skill and its full instructions are not already provided below, load them with the read_skill tool before answering.'
    )
    for (const s of triggered) {
      try {
        parts.push(`Skill "${s.id}" instructions (follow these for matching tasks):\n${getSkillBody(s.id)}`)
      } catch {
        // skip unreadable skill
      }
    }
  }

  if (conv.projectId) {
    try {
      const project = getProject(conv.projectId)
      if (project.instructions.trim()) {
        parts.push(`Project instructions:\n${project.instructions.trim()}`)
      }
      const lastUser = [...conv.messages].reverse().find((m) => m.role === 'user')
      if (project.files.length > 0 && lastUser) {
        const excerpts = await retrieve(conv.projectId, lastUser.content, 6)
        if (excerpts.length > 0) {
          const blocks = excerpts
            .map((e) => `--- From "${e.fileName}" ---\n${e.text}`)
            .join('\n\n')
          parts.push(
            `Relevant excerpts from the project's attached files (retrieved for the latest question — cite the file name when you use them):\n\n${blocks}`
          )
        }
      }
    } catch {
      // project may have been deleted; chat should still work
    }
  }

  return parts.length > 0 ? parts.join('\n\n') : undefined
}
